# Targeted Maximum Likelihood Estimation (TMLE) {#chap_tmle}

When estimating a mean counterfactual outcome using g-computation methods, we have to estimate some $\bar{Q}$ functions (functions of the outcome conditional on the exposures and confounders, $\bar{Q}=\mathbb{E}\left(Y\mid A,L(0)\right)$). For example, the Average Total Effect (ATE) is defined as a marginal effect, based on the empirical mean of such $\bar{Q}$ functions: 
\begin{equation*}
\hat{\Psi}^{\text{ATE}}_{\text{gcomp}} = \frac{1}{n} \sum_{i=1}^n \left[ \hat{\overline{Q}}(A=1)_i - \hat{\overline{Q}}(A=0)_i \right]
\end{equation*}

Unless the $\bar{Q}$ functions are not misspecified, its estimate is expected to be biased (especially if the set of baseline confounders $L(0)$ is high dimensional, for example if it includes is a large number of variables or continuous variables). In order to improve the estimation of $\bar{Q}(A,L)$, it is possible to use data-adaptive methods (machine learning algorithms) in order to optimize the bias-variance trade-off. However, this bias-variance trade-off would be optimized for the $\bar{Q}$ functions, not for the ATE estimate $\hat{\Psi}^\text{ATE}_\text{gcomp}$. If the $\bar{Q}$ function is unknown and has to be estimated (preferably by data-adaptive methods), it can be shown that the g-computation estimate of $\Psi^\text{ATE}$ is asymptotically biased.

The Targeted Maximum Likelihood Estimation (TMLE) method has been developed as an asymptotically linear estimator, so that the estimation of any target parameter in any semiparametric statistical model is unbiased and efficient. In order to estimate a parameter $\Psi(P_0)$, where $P_0$ is an unknown probability distribution among a set $\mathcal{M}$ of possible statistical models, the TMLE is described as a two-step procedure [@vanderlaan_book2011]:

  - The first step is to obtain an initial estimate of the relevant part $\bar{Q}_0$ of the probability distribution $P_0$. Data adaptive methods (machine learning algorithms) can be used to optimize this first step.
  - The second step is to update the initial fit in order to "target toward making an optimal bias-variance tradeoff for the parameter of interest" $\Psi(\bar{Q})$. 

Several R packages have been developed in order to carry out TMLE estimation of causal effects. We will begin using the `ltmle` package, as it can be used to estimate ATE or CDE. More generally, this package can be used to estimate the counterfactual effects of repeated exposure in time-to-event settings. It can also be used in simpler settings with only one binary or continuous outcome, measure only once at the end a the study.

## TMLE for the ATE
In order to illustrate the TMLE procedure, the estimation of a mean counterfactual outcome, denoted $\Psi(A=1) = \mathbb{E} \left[\bar{Q}(A=1,L(0))\right]$, will be described in detail, following the algorithm implemented in the `ltmle` package.

The basic steps of the procedure are the following [@vanderlaan_book2011]:

1. Estimate $\bar{Q}_0$. Data-adaptive methods can be used here, the `ltmle` package relies on the `SuperLearner` package to fit and predict $\hat{\bar{Q}}(A=1)$.

2. Estimate the treatment mechanism $g(A=1 \mid L(0))$. Once again, data-adaptive methods can be used to improve the estimation.

3. The initial estimator of $\bar{Q}_0(A=1)$ will be slightly modified using a parametric fluctuation model, in order to reduce the bias when estimating the ATE. For example, the following parametric model of $\bar{Q}_0(A=1)$ and a "clever covariate" $H = \frac{I(A=1)}{\hat{g}(A=1 \mid L(0))}$ can be applied:
\begin{equation*}
 \text{logit} P(Y \mid \hat{\bar{Q}}, H) = \hat{\bar{Q}} + \varepsilon H
\end{equation*}
The parametric fluctuation model is chosen so that the derivative of its log-likelihood loss function is equal to the appropriate component of the efficient influence curve of the target parameter $\Psi(A=1)$.

4. Modify the initial estimator of $\bar{Q}_0(A=1)$ with the parametric fluctuation model (using the estimation $\hat{\varepsilon}$ from the previous step). We denote $\hat{\bar{Q}}^*(A=1)$ the updated value of $\hat{\bar{Q}}(A=1)$

5. Use the updated values $\hat{\bar{Q}}^*(A=1)$ in the substitution estimator to estimate the target parameter $\Psi(A=1)$ : 
\begin{equation*}
\hat{\Psi}(A=1)_\text{TMLE} = \frac{1}{n} \sum_{i=1}^n \hat{\bar{Q}}^* (A=1,L(0)) 
\end{equation*}

6. Estimate the efficient influence curve $D^*(Q_0,g_0)$ : 
\begin{equation*}
D^*(Q_0,g_0) = \frac{I(A=1)}{g_0(A=1 \mid L(0))}(Y - \bar{Q}_0(A,L(O))) + \bar{Q}_0(A=1,L(0))  + \Psi(A=1)
\end{equation*}

The variance of the target parameter can then be calculated using the variance of the efficient influence curve:
\begin{equation*}
\text{var} \hat{\Psi}(A=1)_\text{TMLE} = \frac{\text{var} \hat{D}^*}{n}
\end{equation*}
